input: keyboard: fix jenkins error for pxa27x_keypad
coccicheck_output/drivers/input/keyboard/pxa27x_keypad.c:928:3-9: ERROR:
missing clk_put; clk_get on line 848 and execution via conditional on
line 925

coccicheck_output/drivers/input/keyboard/pxa27x_keypad.c:939:4-10:
ERROR: missing clk_put; clk_get on line 848 and execution via
conditional on line 936

coccicheck_output/drivers/input/keyboard/pxa27x_keypad.c:928:3-9: ERROR:
missing iounmap; ioremap on line 841 and execution via conditional on
line 925

coccicheck_output/drivers/input/keyboard/pxa27x_keypad.c:939:4-10:
ERROR: missing iounmap; ioremap on line 841 and execution via
conditional on line 936

Change-Id: I48bd6365c8410db67bfbb5d97f49eb17c8291e95
Signed-off-by: Jane Li <jiel@marvell.com>