debug: mmp-log: add the missed header file for arch32
In arm platform, it needs to include this header file

drivers/marvell/debug/mmp-log.c: In function 'mmp_log_buf_init':
drivers/marvell/debug/mmp-log.c:183:3: error: implicit declaration of function 'vmap' [-Werror=implicit-function-declaration]
drivers/marvell/debug/mmp-log.c:183:35: error: 'VM_MAP' undeclared (first use in this function)
drivers/marvell/debug/mmp-log.c:183:35: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors

Change-Id: Id1e39cd8cae7ef777b8c86fc39913d5b18522b55
Signed-off-by: Dongjiu Geng <djgeng@marvell.com>